apiVersion: apps/v1
kind: StatefulSet
metadata:
  name:mongodb-standalone
spec:
  serviceName: database
  replicas: 1
  selector:
    matchLabels:
      labels:
        app: database
        selector: mongodb-standalone
    spec:
      containers:
      - name: mongodb-standalone
        image: mongo:4.0.8
---
apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database
spec:
  ClusterIP: None
  selector:
    app: database
---
